###############################################################################
# Athena
# Logging Configuration
###############################################################################

###############################################################################
# Logger
###############################################################################

logger:

  name: Athena

  level: INFO

###############################################################################
# Console
###############################################################################

console:

  enabled: true

###############################################################################
# File Logging
###############################################################################

file:

  enabled: true

  path: outputs/logs/athena.log

###############################################################################
# Log Format
###############################################################################

format:

  standard: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

  date: "%Y-%m-%d %H:%M:%S"

###############################################################################
# Rotation
###############################################################################

rotation:

  enabled: false

  max_bytes: 10485760

  backup_count: 5