###############################################################################
# Athena
# Model Configuration
###############################################################################

###############################################################################
# Embedding Models
###############################################################################

embedding:

  model_name: sentence-transformers/all-MiniLM-L6-v2
  normalize_embeddings: true


###############################################################################
# Cross Encoder
###############################################################################

cross_encoder:

  model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
  rerank_input_size: 300

###############################################################################
# Future Models
###############################################################################

future:

  reranker: null

  llm: null

  classifier: null