###############################################################################
# Athena
# Ranking Configuration
###############################################################################

###############################################################################
# Cross Encoder
###############################################################################

cross_encoder:

  batch_size: 32

###############################################################################
# Final Ranking
###############################################################################

ranking:

  final_top_k: 100

  assign_ranks: true

  normalize_scores: true

###############################################################################
# Score Fusion
###############################################################################

fusion:

  enable_score_fusion: true

###############################################################################
# Output
###############################################################################

output:

  store_semantic_score: true

  store_feature_score: true

  store_final_score: true

  store_rank: true