"""
Project : Athena
Module  : Core Interfaces

Purpose
-------
Defines the abstract interfaces used throughout Athena.

Guidelines
----------
- Every executable component must inherit from AthenaComponent.
- Every component follows the same lifecycle.
- This ensures consistency across the entire pipeline.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class AthenaComponent(ABC):
    """
    Abstract base interface for every executable component in Athena.

    Lifecycle
    ---------
    initialize()
        Prepare resources required by the component.

    execute()
        Execute the primary logic of the component.

    validate()
        Validate the component's output.

    cleanup()
        Release allocated resources.
    """

    @abstractmethod
    def initialize(self) -> None:
        """
        Initialize the component.

        This method should prepare any resources required before execution,
        such as loading models, creating indices, or allocating memory.
        """
        raise NotImplementedError

    @abstractmethod
    def execute(self, *args: Any, **kwargs: Any) -> Any:
        """
        Execute the primary functionality of the component.

        Parameters
        ----------
        *args
            Positional arguments required by the implementation.

        **kwargs
            Keyword arguments required by the implementation.

        Returns
        -------
        Any
            Component-specific output.
        """
        raise NotImplementedError

    @abstractmethod
    def validate(self) -> bool:
        """
        Validate the output generated by the component.

        Returns
        -------
        bool
            True if validation succeeds, otherwise False.
        """
        raise NotImplementedError

    @abstractmethod
    def cleanup(self) -> None:
        """
        Release resources allocated by the component.

        This method should clean up temporary files, memory,
        open connections, or other allocated resources.
        """
        raise NotImplementedError


###############################################################################
# END OF FILE
###############################################################################